package com.example.jobhive.datastore

data class City(
    val name: String,
    val weather: String,
    val mediumLifeCost: Int,
    val criminalityRisk: String,
    val nightlife: String,
    val occupation: String,
    val hobbies: List<String>,
    val location: String,
    var score: Int,
)

val USAcityList = listOf(
    City(
        name = USAcities.AUSTIN.value,
        weather = "Hot",
        mediumLifeCost = 100000,
        criminalityRisk = "Medium",
        nightlife = "High",
        occupation = "Engineering",
        hobbies = listOf("Nature"),
        location = "Desert",
        score = 0
    ),
    City(
        name = USAcities.TALLAHASSEE.value,
        weather = "Hot",
        mediumLifeCost = 60000,
        criminalityRisk = "Medium",
        nightlife = "Low",
        occupation = "Politics",
        hobbies = listOf("Art"),
        location = "City",
        score = 0
    ),
    City(
        name = USAcities.SALEM.value,
        weather = "Cold",
        mediumLifeCost = 0,
        criminalityRisk = "High",
        nightlife = "Medium",
        occupation = "Humanistic Studies",
        hobbies = listOf("Other"),
        location = "City",
        score = 0
    ),
    City(
        name = USAcities.PHOENIX.value,
        weather = "Hot",
        mediumLifeCost = 70000,
        criminalityRisk = "Medium",
        nightlife = "Medium",
        occupation = "Technology",
        hobbies = listOf("Nature"),
        location = "Desert",
        score = 0
    ),
    City(
        name = USAcities.DENVER.value,
        weather = "Temperate",
        mediumLifeCost = 75000,
        criminalityRisk = "Medium",
        nightlife = "High",
        occupation = "Finance",
        hobbies = listOf("Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = USAcities.HARTFORD.value,
        weather = "Humid subtropical",
        mediumLifeCost = 65000,
        criminalityRisk = "Medium",
        nightlife = "Low",
        occupation = "Insurance",
        hobbies = listOf("Nature"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.ATLANTA.value,
        weather = "Humid subtropical",
        mediumLifeCost = 80000,
        criminalityRisk = "Medium",
        nightlife = "High",
        occupation = "Business",
        hobbies = listOf("Other"),
        location = "Piedmont",
        score = 0
    ),
    City(
        name = USAcities.HONOLULU.value,
        weather = "Tropical rainforest",
        mediumLifeCost = 100000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Tourism",
        hobbies = listOf("Nature"),
        location = "Island",
        score = 0
    ),
    City(
        name = USAcities.BOISE.value,
        weather = "Temperate",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = USAcities.SPRINGFIELD.value,
        weather = "Humid continental",
        mediumLifeCost = 60000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Education",
        hobbies = listOf("Art"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.INDIANAPOLIS.value,
        weather = "Humid continental",
        mediumLifeCost = 70000,
        criminalityRisk = "Medium",
        nightlife = "Medium",
        occupation = "Engineering",
        hobbies = listOf("Other"),
        location = "Prairie",
        score = 0
    ),
    City(
        name = USAcities.TOPEKA.value,
        weather = "Humid continental",
        mediumLifeCost = 60000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Nature"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.FRANKFORT.value,
        weather = "Humid subtropical",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Education",
        hobbies = listOf("Art"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.BATONROUGE.value,
        weather = "Humid subtropical",
        mediumLifeCost = 60000,
        criminalityRisk = "High",
        nightlife = "Medium",
        occupation = "Petroleum",
        hobbies = listOf("Sport"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.AUGUSTA.value,
        weather = "Humid subtropical",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Nature"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.ANNAPOLIS.value,
        weather = "Humid subtropical",
        mediumLifeCost = 65000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Defense",
        hobbies = listOf("Art"),
        location = "Bay",
        score = 0
    ),
    City(
        name = USAcities.BOSTON.value,
        weather = "Cold",
        mediumLifeCost = 55000,
        criminalityRisk = "Medium",
        nightlife = "Medium",
        occupation = "Health",
        hobbies = listOf("Nature"),
        location = "Coastline",
        score = 0
    ),
    City(
        name = USAcities.LANSING.value,
        weather = "Humid continental",
        mediumLifeCost = 60000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Art"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.STPAUL.value,
        weather = "Cold",
        mediumLifeCost = 60000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Sport"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.JACKSON.value,
        weather = "Humid subtropical",
        mediumLifeCost = 50000,
        criminalityRisk = "High",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Nature"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.JEFFERSONCITY.value,
        weather = "Humid subtropical",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Art"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.HELENA.value,
        weather = "Cold",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Nature"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = USAcities.LINCOLN.value,
        weather = "Humid continental",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Other"),
        location = "Prairie",
        score = 0
    ),

    City(
        name = USAcities.CARSONCITY.value,
        weather = "Cold",
        mediumLifeCost = 4500,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Nature"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = USAcities.CONCORD.value,
        weather = "Humid continental",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Nature"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.TRENTON.value,
        weather = "Humid subtropical",
        mediumLifeCost = 60000,
        criminalityRisk = "Medium",
        nightlife = "Low",
        occupation = "Education",
        hobbies = listOf("Art"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.SANTAFE.value,
        weather = "Cold",
        mediumLifeCost = 50000,
        criminalityRisk = "Medium",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Nature"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = USAcities.ALBANY.value,
        weather = "Humid continental",
        mediumLifeCost = 60000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Other"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.HARRISBURG.value,
        weather = "Humid continental",
        mediumLifeCost = 55000,
        criminalityRisk = "Medium",
        nightlife = "Low",
        occupation = "Education",
        hobbies = listOf("Art"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.PROVIDENCE.value,
        weather = "Humid continental",
        mediumLifeCost = 60000,
        criminalityRisk = "Medium",
        nightlife = "Low",
        occupation = "Health",
        hobbies = listOf("Art"),
        location = "Coastline",
        score = 0
    ),
    City(
        name = USAcities.COLUMBIA.value,
        weather = "Humid subtropical",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Education",
        hobbies = listOf("Nature"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.PIERRE.value,
        weather = "Humid continental",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Nature"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.NASHVILLE.value,
        weather = "Humid subtropical",
        mediumLifeCost = 55000,
        criminalityRisk = "Medium",
        nightlife = "High",
        occupation = "Music",
        hobbies = listOf("Sport"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.AUSTIN.value,
        weather = "Hot",
        mediumLifeCost = 100000,
        criminalityRisk = "Medium",
        nightlife = "High",
        occupation = "Engineering",
        hobbies = listOf("Nature"),
        location = "Desert",
        score = 0
    ),

    City(
        name = USAcities.MONTGOMERY.value,
        weather = "Humid subtropical",
        mediumLifeCost = 55000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Politics",
        hobbies = listOf("Art"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.JUNEAU.value,
        weather = "Marine west coast",
        mediumLifeCost = 70000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Oil",
        hobbies = listOf("Nature"),
        location = "Coastline",
        score = 0
    ),
    City(
        name = USAcities.PHOENIX.value,
        weather = "Hot",
        mediumLifeCost = 70000,
        criminalityRisk = "Medium",
        nightlife = "High",
        occupation = "Finance",
        hobbies = listOf("Nature"),
        location = "Desert",
        score = 0
    ),
    City(
        name = USAcities.LITTLEROCK.value,
        weather = "Humid subtropical",
        mediumLifeCost = 60000,
        criminalityRisk = "Medium",
        nightlife = "Medium",
        occupation = "Health",
        hobbies = listOf("Art"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.SACRAMENTO.value,
        weather = "Mediterranean",
        mediumLifeCost = 70000,
        criminalityRisk = "Medium",
        nightlife = "Medium",
        occupation = "Government",
        hobbies = listOf("Sport"),
        location = "Coastline",
        score = 0
    ),
    City(
        name = USAcities.DENVER.value,
        weather = "Cold",
        mediumLifeCost = 70000,
        criminalityRisk = "Medium",
        nightlife = "Medium",
        occupation = "Finance",
        hobbies = listOf("Nature"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = USAcities.HARTFORD.value,
        weather = "Humid continental",
        mediumLifeCost = 70000,
        criminalityRisk = "Medium",
        nightlife = "Low",
        occupation = "Finance",
        hobbies = listOf("Art"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.DOVER.value,
        weather = "Humid subtropical",
        mediumLifeCost = 60000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Government",
        hobbies = listOf("Nature"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.TALLAHASSEE.value,
        weather = "Hot",
        mediumLifeCost = 60000,
        criminalityRisk = "Medium",
        nightlife = "Low",
        occupation = "Politics",
        hobbies = listOf("Art"),
        location = "City",
        score = 0
    ),
    City(
        name = USAcities.ATLANTA.value,
        weather = "Humid subtropical",
        mediumLifeCost = 70000,
        criminalityRisk = "Medium",
        nightlife = "High",
        occupation = "Music",
        hobbies = listOf("Sport"),
        location = "River",
        score = 0
    ),
    City(
        name = USAcities.WASHINGTON.value,
        weather = "Humid subtropical",
        mediumLifeCost = 80000,
        criminalityRisk = "Medium",
        nightlife = "High",
        occupation = "Politics",
        hobbies = listOf("Art", "Nature"),
        location = "River",
        score = 0
    )

)

enum class USAcities(val value: String) {
    MONTGOMERY("Montgomery"),
    JUNEAU("Juneau"),
    PHOENIX("Phoenix"),
    LITTLEROCK("Little Rock"),
    SACRAMENTO("Sacramento"),
    DENVER("Denver"),
    HARTFORD("Hartford"),
    DOVER("Dover"),
    TALLAHASSEE("Tallahassee"),
    ATLANTA("Atlanta"),
    HONOLULU("Honolulu"),
    BOISE("Boise"),
    SPRINGFIELD("Springfield"),
    INDIANAPOLIS("Indianapolis"),
    DESMOINES("Des Moines"),
    TOPEKA("Topeka"),
    FRANKFORT("Frankfort"),
    BATONROUGE("Baton Rouge"),
    AUGUSTA("Augusta"),
    ANNAPOLIS("Annapolis"),
    BOSTON("Boston"),
    LANSING("Lansing"),
    STPAUL("St. Paul"),
    JACKSON("Jackson"),
    JEFFERSONCITY("Jefferson City"),
    HELENA("Helena"),
    LINCOLN("Lincoln"),
    CARSONCITY("Carson City"),
    CONCORD("Concord"),
    TRENTON("Trenton"),
    SANTAFE("Santa Fe"),
    ALBANY("Albany"),
    RALEIGH("Raleigh"),
    BISMARCK("Bismarck"),
    COLUMBUS("Columbus"),
    OKLAHOMACITY("Oklahoma City"),
    SALEM("Salem"),
    HARRISBURG("Harrisburg"),
    PROVIDENCE("Providence"),
    COLUMBIA("Columbia"),
    PIERRE("Pierre"),
    NASHVILLE("Nashville"),
    AUSTIN("Austin"),
    SALTWAKECITY("Salt Lake City"),
    MONTPELIER("Montpelier"),
    RICHMOND("Richmond"),
    OLYMPIA("Olympia"),
    CHARLESTON("Charleston"),
    MADISON("Madison"),
    CHEYENNE("Cheyenne"),
    WASHINGTON("Whashington");

    companion object {
        fun fromString(value: String) = USAcities.values().first { it.value == value }
    }
}

val swissCityList = listOf(

    City(
        name = SWISSCities.FRIBOURG.value,
        weather = "Temperate",
        mediumLifeCost = 70000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Humanistic studies",
        hobbies = listOf("Nature", "Pop-culture"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.SOLOTHURN.value,
        weather = "Temperate",
        mediumLifeCost = 70000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Engineering",
        hobbies = listOf("Nature", "Hiking"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.CHUR.value,
        weather = "Temperate",
        mediumLifeCost = 30000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking", "Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.LIESTAL.value,
        weather = "Temperate",
        mediumLifeCost = 20000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Health",
        hobbies = listOf("Hiking", "Nature"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.AARAU.value,
        weather = "Temperate",
        mediumLifeCost = 85000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Engineering",
        hobbies = listOf("Hiking", "Nature"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.SARNEN.value,
        weather = "Temperate",
        mediumLifeCost = 20000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking", "Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.APPENZELL.value,
        weather = "Temperate",
        mediumLifeCost = 80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking", "Nature"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.ALTDORF.value,
        weather = "Temperate",
        mediumLifeCost = 30000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking", "Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.DELEMONT.value,
        weather = "Temperate",
        mediumLifeCost = 80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Engineering",
        hobbies = listOf("Hiking", "Sport"),
        location = "City",
        score = 0
    ),

    City(
        name = SWISSCities.FRIBOURG.value,
        weather = "Temperate",
        mediumLifeCost = 65000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Education",
        hobbies = listOf("Nature", "Pop-culture"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.SOLOTHURN.value,
        weather = "Temperate",
        mediumLifeCost = 80000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Engineering",
        hobbies = listOf("Nature", "Hiking"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.CHUR.value,
        weather = "Temperate",
        mediumLifeCost = 20000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Tourism",
        hobbies = listOf("Hiking", "Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.LIESTAL.value,
        weather = "Temperate",
        mediumLifeCost = 80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Health",
        hobbies = listOf("Hiking", "Pop-culture"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.AARAU.value,
        weather = "Temperate",
        mediumLifeCost = 85000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Engineering",
        hobbies = listOf("Hiking", "Nature"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.SARNEN.value,
        weather = "Temperate",
        mediumLifeCost = 80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking", "Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.APPENZELL.value,
        weather = "Temperate",
        mediumLifeCost = 10000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking", "Nature"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.ALTDORF.value,
        weather = "Temperate",
        mediumLifeCost = 30000,
        criminalityRisk = "High",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking", "Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.DELEMONT.value,
        weather = "Temperate",
        mediumLifeCost = 80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Engineering",
        hobbies = listOf("Hiking", "Nature"),
        location = "City",
        score = 0
    ),
    City(
       name = SWISSCities.JURA.value,
        weather = "Cold",
        mediumLifeCost = 80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Engineering",
        hobbies = listOf("Hiking", "Nature"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.VS.value,
        weather="Cold",
        mediumLifeCost=40000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.BE.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Engineering",
        hobbies = listOf("Pop-culture","Hiking"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.SO.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.BSBL.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.AG.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.LU.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Engineering",
        hobbies = listOf("Pop-culture","Hiking"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.OWNW.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.SH.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Engineering",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.ZH.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Engineering",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.ZG.value,
        weather="Temperate",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Engineering",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.SZ.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.UR.value,
        weather="Cold",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.TI.value,
        weather="Temperate",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Engineering",
        hobbies = listOf("Hiking","Pop-culture"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.TG.value,
        weather="Temperate",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.SG.value,
        weather="Temperate",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "High",
        occupation = "Engineering",
        hobbies = listOf("Hiking","Pop-culture"),
        location = "City",
        score = 0
    ),
    City(
        name = SWISSCities.GL.value,
        weather="Temperate",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.ARAI.value,
        weather="Temperate",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Low",
        occupation = "Humanistic studies",
        hobbies = listOf("Hiking","Sport"),
        location = "Mountain",
        score = 0
    ),
    City(
        name = SWISSCities.GR.value,
        weather="Temperate",
        mediumLifeCost=80000,
        criminalityRisk = "Low",
        nightlife = "Medium",
        occupation = "Humanistic studies",
        hobbies = listOf("Nature","Sport"),
        location = "Mountain",
        score = 0
    )
)

enum class SWISSCities(val value: String) {
    //insert all swiss cantons cities
    BASEL("Basel"),
    BERN("Bern"),
    GENEVA("Geneva"),
    LAUSANNE("Lausanne"),
    LUCERNE("Lucerne"),
    STGALLEN("St. Gallen"),
    ZURICH("Zurich"),
    FRIBOURG("Fribourg"),
    SOLOTHURN("Solothurn"),
    CHUR("Chur"),
    LIESTAL("Liestal"),
    AARAU("Aarau"),
    SARNEN("Sarnen"),
    APPENZELL("Appenzell"),
    ALTDORF("Altdorf"),
    DELEMONT("Delemont"),
    SOLETTA("Soleta"),
    SION("Sion"),
    NEUCHATEL("Neuchatel"),
    JURA("Jura"),
    VS("VS"),
    BE("BE"),
    SO("SO"),
    BSBL("BS/BL"),
    AG("AG"),
    LU("LU"),
    SH("SH"),
    ZH("ZH"),
    ZG("ZG"),
    SZ("SZ"),
    UR("UR"),
    TI("TI"),
    TG("TG"),
    SG("SG"),
    GL("GL"),
    ARAI("AR/AI"),
    GR("GR"),
    OWNW("ow/nw")
    ;

    companion object {
        fun fromString(value: String) = values().first { it.value.equals(value, ignoreCase = true) }
    }
}
